"""docker-compose isolation: reading the compose model through Compose itself (research.md §4).

Compose runs as a subprocess. wtenv has no YAML library and no Docker SDK: it reads the output of
`docker compose config --format json`, so what it sees is what Compose will later run. This
module is imported only when `[compose]` is configured (research.md §8).
"""

import json
import os
import posixpath
import re
import subprocess
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Protocol
from urllib.parse import urlsplit

from wtenv.config import COMPOSE_FILE_NAMES
from wtenv.database import Removal
from wtenv.envfile import write_atomic
from wtenv.errors import ErrorCode, JsonValue, WtenvError
from wtenv.identity import short_id, slug
from wtenv.output import FailedItem, Item, ItemKind, KeptVolume, WarningCode, WarningInfo

_FILE_SETTING = "compose.file"
# Compose loads one of these beside the compose file; the pairs follow COMPOSE_FILE_NAMES.
OVERRIDE_FILE_NAMES = tuple(name.replace(".y", ".override.y") for name in COMPOSE_FILE_NAMES)
_OVERRIDE_HEADER = (
    "# Generated by wtenv for this worktree. Do not edit or commit; `wtenv up` rewrites it.\n"
)


class Runner(Protocol):
    """Runs a command with an environment and a working directory and returns the process.

    The checks and the resolution take the runner as a parameter, so tests need no Docker.
    """

    def __call__(
        self, command: Sequence[str], environ: Mapping[str, str], cwd: Path | None
    ) -> "subprocess.CompletedProcess[str]":
        """Run `command`; a non-zero exit status is not an error.

        Raises `FileNotFoundError` when the program is not installed.
        """
        ...


def run_command(
    command: Sequence[str], environ: Mapping[str, str], cwd: Path | None
) -> "subprocess.CompletedProcess[str]":
    """Run `command` with exactly `environ`, in `cwd`, and capture its text output."""
    return subprocess.run(
        list(command),
        env=dict(environ),
        cwd=cwd,
        capture_output=True,
        text=True,
        stdin=subprocess.DEVNULL,
        check=False,
    )


@dataclass(frozen=True)
class PortMapping:
    """One port mapping of a service, with the fields Compose reported for it."""

    service: str
    target: int  # the container port
    protocol: str
    host_ip: str | None
    # The host port as Compose reports it: a string, or None when the mapping has none ("3000").
    published: str | None
    mode: str | None
    name: str | None
    app_protocol: str | None


@dataclass(frozen=True)
class ComposeModel:
    """What wtenv needs of a resolved compose file: its port mappings and its warnings."""

    mappings: list[PortMapping]
    warnings: list[WarningInfo]


# --- resolving the compose file (research.md §4, Decision) -------------------------------------


def resolution_command(file: str | Path) -> list[str]:
    """Return the command that resolves `file` with every profile (research.md §4)."""
    return [
        "docker",
        "compose",
        "-f",
        str(file),
        "--profile",
        "*",
        "config",
        "--format",
        "json",
    ]


def marker_environment(variables: Sequence[str]) -> dict[str, str]:
    """Return the marker values: variable `i` of `variables` is set to `i + 1` (data-model.md).

    A published port that resolves to the marker of variable `i` is tied to that variable.
    Markers are used instead of real ports, so the analysis needs no block.
    """
    return {name: str(index + 1) for index, name in enumerate(variables)}


def resolve_model(
    file: Path,
    variables: Sequence[str],
    *,
    run: Runner = run_command,
    environ: Mapping[str, str] | None = None,
) -> ComposeModel:
    """Have Compose resolve `file` with the markers of `variables`, and parse the result.

    Raises `config_invalid` (naming `compose.file`) when Compose cannot resolve the file, and
    `unsupported` for a published range (FR-033). `environ` defaults to the process environment.
    """
    base = os.environ if environ is None else environ
    process = run(
        resolution_command(file),
        {**base, **marker_environment(variables)},
        file.parent,
    )
    if process.returncode != 0:
        raise _unresolvable(file, process.stderr.strip() or f"exit status {process.returncode}")
    try:
        document = json.loads(process.stdout)
    except json.JSONDecodeError as error:
        raise _unresolvable(file, f"its resolved form is not JSON ({error})") from error
    if not isinstance(document, dict):
        raise _unresolvable(file, "its resolved form is not a JSON object")
    return parse_model(document)


def _unresolvable(file: Path, problem: str) -> WtenvError:
    """Build `config_invalid` for a compose file that Compose cannot resolve."""
    return WtenvError(
        ErrorCode.CONFIG_INVALID,
        f"{file}: Compose cannot resolve it: {problem}",
        hint="Check that `docker compose config` works on the file, then run `wtenv up` again. "
        "Nothing was changed.",
        details={"file": str(file), "setting": _FILE_SETTING},
    )


# --- parsing the resolved model ----------------------------------------------------------------


def parse_model(document: Mapping[str, Any]) -> ComposeModel:
    """Return the port mappings and warnings in a resolved compose model.

    Mappings come in service-name order and, within a service, in the order Compose reported.
    A mapping without a host port is kept with `published` None. A published range raises
    `unsupported` (`compose_port_range`, FR-033). A service with `container_name` gets the
    warning `compose_fixed_container_name`.
    """
    services: Mapping[str, Mapping[str, Any]] = document.get("services") or {}
    mappings: list[PortMapping] = []
    warnings: list[WarningInfo] = []
    for service in sorted(services):
        settings = services[service]
        if settings.get("container_name"):
            warnings.append(_fixed_container_name(service, str(settings["container_name"])))
        for entry in settings.get("ports") or []:
            mapping = _mapping(service, entry)
            if mapping.published is not None and "-" in mapping.published:
                raise _port_range(service, mapping.published)
            mappings.append(mapping)
    return ComposeModel(mappings=mappings, warnings=warnings)


def _mapping(service: str, entry: Mapping[str, Any]) -> PortMapping:
    published = entry.get("published")
    return PortMapping(
        service=service,
        target=int(entry["target"]),
        protocol=str(entry.get("protocol", "tcp")),
        host_ip=entry.get("host_ip"),
        published=None if published is None else str(published),
        mode=entry.get("mode"),
        name=entry.get("name"),
        app_protocol=entry.get("app_protocol"),
    )


def _port_range(service: str, published: str) -> WtenvError:
    return WtenvError(
        ErrorCode.UNSUPPORTED,
        f"service {service} publishes the host range {published}; Compose picks any free port "
        "of a range when it starts, so wtenv cannot pin it",
        hint=f"Publish one host port per container port in service {service}.",
        details={"reason": "compose_port_range", "service": service},
    )


def _fixed_container_name(service: str, container_name: str) -> WarningInfo:
    return WarningInfo(
        code=WarningCode.COMPOSE_FIXED_CONTAINER_NAME,
        message=(
            f"service {service} sets container_name {container_name}; two worktrees cannot "
            "both run it"
        ),
        details={"service": service, "container_name": container_name},
    )


# --- names and the override file (files.md, Names and Compose override file) -------------------


def project_name(worktree_name: str, git_dir: str) -> str:
    """Return the compose project name `wtenv-<slug>-<id8>` (files.md, Names).

    The caller records it when it first provisions the worktree and never computes it again, so
    the project survives a move (FR-084).
    """
    return f"wtenv-{slug(worktree_name, '-')}-{short_id(git_dir, 8)}"


def override_file_name(compose_file_name: str) -> str:
    """Return the override name for a compose file name: `compose.yaml` -> `compose.override.yaml`.

    Raises `ValueError` for a name other than the four default compose file names; the
    configuration rejects those before this is called.
    """
    if compose_file_name not in COMPOSE_FILE_NAMES:
        raise ValueError(f"{compose_file_name} is not a default compose file name")
    return OVERRIDE_FILE_NAMES[COMPOSE_FILE_NAMES.index(compose_file_name)]


def override_path(compose_file: str) -> str:
    """Return the override file's path beside `compose_file`, in the same form (relative stays)."""
    directory, file_name = posixpath.split(compose_file)
    return posixpath.join(directory, override_file_name(file_name))


def override_text(project: str, assigned: Sequence[tuple[PortMapping, int]]) -> str:
    """Return the text of the override file, byte for byte as files.md lays it out.

    `assigned` pairs each port mapping of the compose model with the host port it was given.
    Services come in name order, each with `ports: !override` and its mappings in the order
    given. A mapping repeats every field Compose reported, with only `published` changed
    (FR-029). Strings use JSON quoting, which YAML reads the same way. The same input always
    gives the same text, so a repeat `up` writes identical bytes.
    """
    lines = [f"name: {json.dumps(project)}"]
    by_service: dict[str, list[str]] = {}
    for mapping, port in assigned:
        by_service.setdefault(mapping.service, []).append(_mapping_line(mapping, port))
    if by_service:
        lines.append("services:")
    for service in sorted(by_service):
        lines.append(f"  {json.dumps(service)}:")
        lines.append("    ports: !override")
        lines += by_service[service]
    return _OVERRIDE_HEADER + "\n".join(lines) + "\n"


def _mapping_line(mapping: PortMapping, port: int) -> str:
    """Return one `ports` entry: target, published, protocol, mode, then the optional fields."""
    fields: dict[str, object] = {
        "target": mapping.target,
        "published": str(port),
        "protocol": mapping.protocol,
        "mode": mapping.mode,
        "host_ip": mapping.host_ip,
        "name": mapping.name,
        "app_protocol": mapping.app_protocol,
    }
    present = {key: value for key, value in fields.items() if value is not None}
    return f"      - {json.dumps(present)}"


# --- the limit checks (research.md §4, "v1 limits", and §11) -----------------------------------

MINIMUM_COMPOSE_VERSION = (2, 24, 4)  # `!override` needs it (research.md §4)
_LOCAL_DOCKER_HOSTS = ("localhost", "127.0.0.1", "::1")  # `urlsplit` gives IPv6 without brackets
_ENV_OVERRIDES = ("COMPOSE_PROJECT_NAME", "COMPOSE_FILE")  # both outrank the override file
_ENV_ASSIGNMENT = re.compile(r"\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)")
_VERSION = re.compile(r"v?(\d+)\.(\d+)\.(\d+)")


def check_docker(*, run: Runner = run_command, environ: Mapping[str, str] | None = None) -> None:
    """Raise `dependency_unavailable` unless a local Docker with Compose 2.24.4+ is running.

    The endpoint is judged first (`DOCKER_HOST`, else the current context) and must be local
    (FR-035); no command that contacts the engine runs before that. Then the Compose version,
    then the engine. `details.reason` is `not_local`, `not_installed`, `too_old` (with `required`
    and `found`), or `not_running`.
    """
    base = os.environ if environ is None else environ
    host = base.get("DOCKER_HOST") or _context_endpoint(run, base)
    if not _is_local_endpoint(host):
        raise _docker_unavailable("not_local", "the Docker engine is not on this machine")
    found = _compose_version(run, base)
    if _version_tuple(found) < MINIMUM_COMPOSE_VERSION:
        raise _docker_unavailable(
            "too_old",
            f"Docker Compose {found} is older than 2.24.4, which `!override` needs",
            required="2.24.4",
            found=found,
        )
    if _command(run, ["docker", "info", "--format", "{{.ServerVersion}}"], base).returncode != 0:
        raise _docker_unavailable("not_running", "the Docker engine does not answer")


def _command(
    run: Runner, command: Sequence[str], environ: Mapping[str, str]
) -> "subprocess.CompletedProcess[str]":
    """Run `command`; a missing program is `dependency_unavailable` (`not_installed`)."""
    try:
        return run(command, environ, None)
    except FileNotFoundError as error:
        raise _docker_unavailable("not_installed", f"{command[0]} is not installed") from error


def _context_endpoint(run: Runner, environ: Mapping[str, str]) -> str:
    """Return the endpoint of the current Docker context."""
    command = ["docker", "context", "inspect", "--format", "{{.Endpoints.docker.Host}}"]
    process = _command(run, command, environ)
    if process.returncode != 0:
        raise _docker_unavailable("not_running", "the current Docker context cannot be read")
    return process.stdout.strip()


def _is_local_endpoint(host: str) -> bool:
    """Return whether `host` is a `unix://` socket or a `tcp://` address on this machine."""
    parts = urlsplit(host)
    if parts.scheme == "unix":
        return True
    return parts.scheme == "tcp" and parts.hostname in _LOCAL_DOCKER_HOSTS


def _compose_version(run: Runner, environ: Mapping[str, str]) -> str:
    """Return the Compose version without a leading `v`, e.g. `2.24.4`."""
    process = _command(run, ["docker", "compose", "version", "--short"], environ)
    found = process.stdout.strip().removeprefix("v")
    if process.returncode != 0 or _VERSION.match(found) is None:
        raise _docker_unavailable("not_installed", "Docker Compose is not installed")
    return found


def _version_tuple(version: str) -> tuple[int, int, int]:
    """Return the first three numbers of `version`, e.g. `2.24.4-desktop.1` -> (2, 24, 4)."""
    match = _VERSION.match(version)
    assert match is not None  # `_compose_version` only returns versions that match
    major, minor, patch = match.groups()
    return int(major), int(minor), int(patch)


def _docker_unavailable(reason: str, message: str, **extra: str) -> WtenvError:
    return WtenvError(
        ErrorCode.DEPENDENCY_UNAVAILABLE,
        message,
        hint="Compose isolation needs a local Docker engine and Docker Compose 2.24.4 or later.",
        details={"dependency": "docker", "reason": reason, **extra},
    )


def check_project_is_unused(
    project: str, *, run: Runner = run_command, environ: Mapping[str, str] | None = None
) -> None:
    """Raise `ownership_conflict` when resources labelled with `project` already exist.

    `up` calls it for a worktree with no compose record: the name is generated from the worktree,
    but nothing wtenv recorded created what carries it, so it must not be recorded as wtenv's and
    removed by a later `down` (data-model.md, Resource states; FR-024, FR-039). A worktree that
    records the project is not checked: its resources are wtenv's, and an interrupted run adopts
    them (FR-067). `details.kind` is `compose_project`. Raises `dependency_unavailable` when Docker
    cannot be asked.
    """
    base = os.environ if environ is None else environ
    env = {name: value for name, value in base.items() if not name.startswith("COMPOSE_")}
    try:
        found = _list_project(project, run, env)
    except _DockerFailed as error:
        raise _docker_unavailable("not_running", str(error)) from None
    if found:
        raise WtenvError(
            ErrorCode.OWNERSHIP_CONFLICT,
            f"the compose project {project} already has resources, and wtenv did not create them",
            hint="Take the project down yourself, or rename the worktree's directory; wtenv will "
            "not touch resources it has no record of.",
            details={"kind": ItemKind.COMPOSE_PROJECT.value, "name": project},
        )


def check_override_files(root: Path, compose_file: str, recorded_override: str | None) -> None:
    """Raise `ownership_conflict` for an override file beside the compose file that is not wtenv's.

    Any of the four override names counts, because Compose loads one of them and wtenv never
    modifies or replaces a developer's. `recorded_override` is the registry's override path
    (relative to `root`); that file passes. The file is left as it is (research.md §4).
    """
    directory = posixpath.dirname(compose_file)
    for name in OVERRIDE_FILE_NAMES:
        relative = posixpath.join(directory, name)
        path = root / relative
        if os.path.lexists(path) and relative != recorded_override:
            raise WtenvError(
                ErrorCode.OWNERSHIP_CONFLICT,
                f"{path} exists and wtenv did not create it; Compose loads only one override",
                hint="Move your override into the compose file, or remove it, then run "
                "`wtenv up` again. Nothing was changed.",
                details={"kind": "compose_override", "name": str(path)},
            )


def check_environment(root: Path, compose_file: str, environ: Mapping[str, str]) -> None:
    """Raise `unsupported` when `COMPOSE_PROJECT_NAME` or `COMPOSE_FILE` would beat the override.

    Both are looked for in `environ` and in `.env` beside the compose file (`details.file` names
    it). An empty value does not count: Compose ignores it. The values are never printed.
    """
    for variable in _ENV_OVERRIDES:
        if environ.get(variable):
            raise _env_override(variable, "the environment", None)
    dot_env = root / posixpath.join(posixpath.dirname(compose_file), ".env")
    try:
        text = dot_env.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return
    for line in text.splitlines():
        match = _ENV_ASSIGNMENT.fullmatch(line)
        if match is not None and match.group(1) in _ENV_OVERRIDES and match.group(2).strip():
            raise _env_override(match.group(1), str(dot_env), str(dot_env))


def _env_override(variable: str, where: str, file: str | None) -> WtenvError:
    details: dict[str, JsonValue] = {"reason": "compose_env_override", "variable": variable}
    if file is not None:
        details["file"] = file
    return WtenvError(
        ErrorCode.UNSUPPORTED,
        f"{variable} is set in {where}; it outranks the override file, so the worktree would "
        "not be isolated",
        hint=f"Unset {variable}, then run `wtenv up` again. Nothing was changed.",
        details=details,
    )


# --- writing and verifying the override (research.md §4) ---------------------------------------

_OVERRIDE_MODE = 0o644  # a generated file that Compose and the developer read


def write_override(path: Path, text: str) -> Literal["created", "updated", "unchanged"]:
    """Write `text` to `path` through a temporary file and an atomic rename.

    Returns what happened. A file that already holds `text` is not touched, so a repeat `up`
    leaves identical bytes (US3 scenario 4).
    """
    try:
        current: str | None = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current == text:
        return "unchanged"
    write_atomic(path, text.encode("utf-8"), _OVERRIDE_MODE)
    return "created" if current is None else "updated"


def verify_override(
    root: Path,
    compose_file: str,
    project: str,
    assigned: Sequence[tuple[PortMapping, int]],
    *,
    run: Runner = run_command,
    environ: Mapping[str, str] | None = None,
) -> None:
    """Check that plain Compose, run the way a developer runs it, uses the override.

    Runs `docker compose --profile "*" config --format json` in the compose file's directory.
    The project name must be `project`, and the published ports must be exactly the assigned
    ones. Otherwise raises `unsupported` (`compose_verification_failed`): isolation would
    silently not apply (FR-033).
    """
    file = root / compose_file
    base = os.environ if environ is None else environ
    process = run(
        ["docker", "compose", "--profile", "*", "config", "--format", "json"], base, file.parent
    )
    if process.returncode != 0:
        raise _verification_failed(file, process.stderr.strip() or "Compose failed")
    try:
        document = json.loads(process.stdout)
        if not isinstance(document, dict):
            raise TypeError("not a JSON object")
        model = parse_model(document)
    except (ValueError, TypeError, WtenvError) as error:
        raise _verification_failed(
            file, f"Compose printed something unexpected ({error})"
        ) from error
    if document.get("name") != project:
        raise _verification_failed(
            file, f"Compose uses the project name {document.get('name')}, not {project}"
        )
    found = {_port_key(m, m.published) for m in model.mappings}
    expected = {_port_key(m, str(port)) for m, port in assigned}
    unexpected = sorted(found - expected)
    if unexpected or found != expected:
        service = (unexpected or sorted(expected - found))[0][0]
        raise _verification_failed(
            file, f"service {service} does not publish exactly the assigned ports"
        )


def _port_key(mapping: PortMapping, published: str | None) -> tuple[str, int, str, str, str]:
    return (
        mapping.service,
        mapping.target,
        mapping.protocol,
        mapping.host_ip or "",
        published or "",
    )


def _verification_failed(file: Path, problem: str) -> WtenvError:
    return WtenvError(
        ErrorCode.UNSUPPORTED,
        f"{file}: the generated override is not in force: {problem}",
        hint="The override was removed. Check the compose file for something wtenv cannot "
        "isolate, such as an `include` that sets ports, then run `wtenv up` again.",
        details={"reason": "compose_verification_failed", "file": str(file)},
    )


def write_and_verify_override(
    root: Path,
    compose_file: str,
    override_file: str,
    project: str,
    assigned: Sequence[tuple[PortMapping, int]],
    text: str,
    *,
    run: Runner = run_command,
    environ: Mapping[str, str] | None = None,
) -> Literal["created", "updated", "unchanged"]:
    """Write the override, then verify it; when verification fails, remove the file just written.

    Returns what happened to the file. Raises `unsupported` (`compose_verification_failed`).
    """
    path = root / override_file
    action = write_override(path, text)
    try:
        verify_override(root, compose_file, project, assigned, run=run, environ=environ)
    except WtenvError:
        path.unlink(missing_ok=True)
        raise
    return action


# --- removing a recorded project (research.md §4; FR-039, FR-042) -------------------------------

PROJECT_LABEL = "com.docker.compose.project"

# The form of a project name wtenv generates (files.md, Names): `wtenv-<slug>-<id8>`.
_GENERATED_PROJECT = re.compile(r"wtenv-[a-z0-9-]{1,40}-[0-9a-f]{8}")


def project_problem(project: str, git_dir: str) -> str | None:
    """Return why `project` is not a name wtenv generated for `git_dir`, or None when it is.

    The registry is a file a person can edit, so `down` and `gc` check a recorded project before
    anything is listed, inspected, or removed (cli.md, `wtenv down`, "Recorded values"): the name
    has the form `wtenv-<slug>-<id8>` in full, and its `<id8>` is that of the entry's own git
    directory, which is the registry key and never changes.
    """
    if _GENERATED_PROJECT.fullmatch(project) and project.endswith(f"-{short_id(git_dir, 8)}"):
        return None
    return (
        "not a project name wtenv generates (wtenv-<name>-<id> of this worktree's git directory); "
        "it was left alone"
    )


# Per kind of resource: the listing command (the label filter and the format are added), the
# format that prints what a removal command names and then the display name, and the removal.
_RESOURCE_KINDS = (
    (ItemKind.COMPOSE_CONTAINER, ["docker", "ps", "-a"], "{{.ID}} {{.Names}}", ["docker", "rm"]),
    (
        ItemKind.COMPOSE_NETWORK,
        ["docker", "network", "ls"],
        "{{.ID}} {{.Name}}",
        ["docker", "network", "rm"],
    ),
    (ItemKind.COMPOSE_VOLUME, ["docker", "volume", "ls"], "{{.Name}}", ["docker", "volume", "rm"]),
)


@dataclass(frozen=True)
class _Resource:
    """A container, network, or volume that carries the recorded project's label."""

    kind: ItemKind
    key: str  # what a removal command names: the id, or the name of a volume
    name: str


class _DockerFailed(Exception):
    """Docker could not be asked or told; the message becomes the reason of a failed item."""


def _first_line(text: str) -> str:
    """Return the first non-empty line of `text`, cut short, for a reason."""
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return lines[0][:200] if lines else ""


def _docker(
    run: Runner, command: Sequence[str], environ: Mapping[str, str], cwd: Path | None = None
) -> "subprocess.CompletedProcess[str]":
    """Run a docker command; a missing `docker` program is `_DockerFailed`."""
    try:
        return run(command, environ, cwd)
    except FileNotFoundError:
        raise _DockerFailed("docker is not installed") from None


def _list_project(project: str, run: Runner, environ: Mapping[str, str]) -> list[_Resource]:
    """Return the containers, networks, and volumes labelled with `project`, in that order.

    A resource with no compose label, such as an `external` volume or network, is never listed,
    and neither is one of another project: the engine filters on the exact label value.
    """
    found = []
    for kind, listing, template, _ in _RESOURCE_KINDS:
        label = f"label={PROJECT_LABEL}={project}"
        process = _docker(run, [*listing, "--filter", label, "--format", template], environ)
        if process.returncode != 0:
            reason = _first_line(process.stderr) or f"exit status {process.returncode}"
            raise _DockerFailed(f"Docker cannot list the project's resources: {reason}")
        for line in process.stdout.splitlines():
            if line.strip():
                key, _, name = line.strip().partition(" ")
                found.append(_Resource(kind, key, name or key))
    return found


# What `docker container inspect` prints per container: the name of each volume it mounts.
_MOUNTED_VOLUMES = '{{range .Mounts}}{{if eq .Type "volume"}}{{.Name}}{{"\\n"}}{{end}}{{end}}'


def _unlabelled_mounts(
    project: str, found: list[_Resource], run: Runner, environ: Mapping[str, str]
) -> list[KeptVolume]:
    """Return the volumes the project's containers mount that do not carry its label (reading R6).

    Docker gives `com.docker.compose.project` only to named volumes. An anonymous volume and an
    `external` one have no label, so the label listing never finds them; the only thing that ties
    them to the project is a mount of one of its containers. They are reported, in name order,
    and are never passed to a removal command (FR-039). This has to run while the containers
    still exist, so before `docker compose down`.
    """
    containers = [r.key for r in found if r.kind is ItemKind.COMPOSE_CONTAINER]
    if not containers:
        return []
    command = ["docker", "container", "inspect", "--format", _MOUNTED_VOLUMES, *containers]
    process = _docker(run, command, environ)
    if process.returncode != 0:
        reason = _first_line(process.stderr) or f"exit status {process.returncode}"
        raise _DockerFailed(f"Docker cannot inspect the project's containers: {reason}")
    labelled = {r.name for r in found if r.kind is ItemKind.COMPOSE_VOLUME}
    mounted = {line.strip() for line in process.stdout.splitlines() if line.strip()}
    return [
        KeptVolume(name=name, project=project, reason="unlabelled")
        for name in sorted(mounted - labelled)
    ]


def remove_project(
    project: str,
    git_dir: str,
    *,
    dry_run: bool = False,
    run: Runner = run_command,
    environ: Mapping[str, str] | None = None,
) -> Removal:
    """Remove the recorded compose project `project`: its containers, networks, and volumes.

    The resources carrying the project's label are listed, and the volumes its containers mount
    without that label are found (`_unlabelled_mounts`). Then `docker compose -p <project> down
    --remove-orphans` runs from a directory with no compose file (research.md §4), and the label
    is listed again. What is still there is removed with `docker rm`, `docker network rm`, and
    `docker volume rm`, each by its id or name; what remains after that is `failed`. `--volumes`
    is never passed: it would remove the anonymous volumes too, which carry no label. Only
    resources with the recorded project's label are ever named in a removal command, so an
    anonymous or `external` volume and an `external` network are never removed (FR-039); the
    volumes found without the label are `kept_volumes` (reading R6). Every removed resource is an
    item; a project with nothing left is `already_absent` (FR-042). `COMPOSE_*` variables are not
    passed on, so they cannot point Compose at another project or file. With `dry_run` only the
    listings and the inspection run, and the same items are returned. When Docker cannot be asked,
    the project is `failed`, in a dry run as in a real one, and is not listed as removed.

    `git_dir` is the entry's git directory. A `project` that is not the name wtenv generates for
    it is `failed` at once: no `docker` command is run, not even a listing (`project_problem`).
    """
    project_item = Item(kind=ItemKind.COMPOSE_PROJECT, name=project)
    problem = project_problem(project, git_dir)
    if problem is not None:
        return Removal(failed=[FailedItem(kind=project_item.kind, name=project, reason=problem)])
    base = os.environ if environ is None else environ
    env = {name: value for name, value in base.items() if not name.startswith("COMPOSE_")}
    try:
        before = _list_project(project, run, env)
        if not before:
            return Removal(already_absent=[project_item])
        kept_volumes = _unlabelled_mounts(project, before, run, env)
        if dry_run:
            return Removal(removed=[_item_of(r) for r in before], kept_volumes=kept_volumes)
        with tempfile.TemporaryDirectory() as empty:
            down = ["docker", "compose", "-p", project, "down", "--remove-orphans"]
            _docker(run, down, env, Path(empty))  # what it leaves behind is checked next
        remaining = _list_project(project, run, env)
        reasons = {r: _remove_resource(r, run, env) for r in remaining}
        left = _list_project(project, run, env)
    except _DockerFailed as error:
        # A dry run that cannot ask Docker fails the project, as the real run would (FR-040).
        reason = str(error)
        return Removal(failed=[FailedItem(kind=project_item.kind, name=project, reason=reason)])
    candidates = before + [r for r in remaining if r not in before]
    return Removal(
        removed=[_item_of(r) for r in candidates if r not in left],
        failed=[
            FailedItem(
                kind=r.kind,
                name=r.name,
                reason=reasons.get(r) or "it was still there after it was removed",
            )
            for r in left
        ],
        kept_volumes=kept_volumes,
    )


def _item_of(resource: _Resource) -> Item:
    return Item(kind=resource.kind, name=resource.name)


def _remove_resource(resource: _Resource, run: Runner, environ: Mapping[str, str]) -> str:
    """Remove one labelled resource that `compose down` left; return why it failed, or ''."""
    removal = next(command for kind, _, _, command in _RESOURCE_KINDS if kind is resource.kind)
    process = _docker(run, [*removal, resource.key], environ)
    if process.returncode == 0:
        return ""
    return _first_line(process.stderr) or f"exit status {process.returncode}"
