"""A hand-edited registry must not make `down` or `gc` touch anything wtenv did not create
(T176 to T178, T211; FR-039, FR-044, FR-086; review 2, findings H1 and H2).

The registry is a file a person can edit. Each test provisions a worktree with `up`, edits one
recorded field in `registry.json` to point at a decoy that the test made outside wtenv, and runs
`down --dry-run`, `down`, `gc` (after `git worktree remove`), and `gc --release` (after the
repository is deleted). In every run the decoy is as it was: the same bytes, the same containers,
the same database. A value of a form wtenv never records is reported under `failed`, its record
stays, the entry stays, and the exit status is 13 (0 for a dry run).

Nothing here touches anything outside its own temporary repository and its own temporary state
directory. The Docker decoys are made by the test, under unique names, and removed by exactly those
names at the end of the test; `postgres-local` and every other container are never looked at.
"""

import json
import os
import shutil
import subprocess
import uuid
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path

import pytest
from helpers import (
    BEGIN,
    END,
    clean_environment,
    commit_all,
    git,
    make_sqlite_template,
    parse_down,
    parse_gc,
    parse_up,
    project_resources,
)

from wtenv.identity import current_worktree, short_id
from wtenv.output import FailedItem, Item
from wtenv.registry import load, registry_path

pytestmark = pytest.mark.integration

Run = Callable[..., "subprocess.CompletedProcess[str]"]
MakeRepo = Callable[[str], Path]
AddWorktree = Callable[[Path, str, str], Path]

MODES = ("dry-run", "down", "gc", "gc-release")
# The worktree directory is gone when `gc` runs, and a directory at its path would make the entry
# `path_exists`, not orphaned. A decoy inside the worktree can therefore only exist in the other
# three modes.
MODES_WITH_A_WORKTREE = ("dry-run", "down", "gc-release")

SQLITE_TOML = '[database]\ntype = "sqlite"\ntemplate = "db/dev.sqlite3"\nurl = "sqlite:///{path}"\n'
OVERRIDE_HEADER = (
    "# Generated by wtenv for this worktree. Do not edit or commit; `wtenv up` rewrites it.\n"
)
SECTION = f"A=1\n{BEGIN}\nPORT=1\n{END}\n".encode()
STACK_IMAGE = "valkey/valkey:latest"


@dataclass
class Case:
    """A provisioned worktree, the repository it belongs to, and a directory to run `gc` in."""

    repo: Path
    worktree: Path
    git_dir: str
    outside: Path
    env: dict[str, str]


def hand_edit(case: Case, change: Callable[[dict[str, object]], None]) -> None:
    """Edit the entry of `case` in `registry.json` as a person with a text editor would."""
    path = registry_path()
    document = json.loads(path.read_text(encoding="utf-8"))
    change(document["worktrees"][case.git_dir])
    path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def provision(
    run_wtenv: Run,
    make_repo: MakeRepo,
    add_worktree: AddWorktree,
    tmp_path: Path,
    *,
    toml: str,
    files: dict[str, str] | None = None,
    env: dict[str, str] | None = None,
) -> Case:
    """Create a repository with `wtenv.toml` and a SQLite template, add a worktree, run `up`."""
    repo = make_repo("app")
    make_sqlite_template(repo / "db" / "dev.sqlite3")
    (repo / "wtenv.toml").write_text(toml, encoding="utf-8")
    for name, text in (files or {}).items():
        (repo / name).write_text(text, encoding="utf-8")
    commit_all(repo)
    worktree = add_worktree(repo, "feature-x", "feature-x")
    process = run_wtenv(["up", "--json"], worktree, env)
    assert process.returncode == 0, process.stdout + process.stderr
    parse_up(process)
    outside = tmp_path / "outside"
    outside.mkdir()
    return Case(repo, worktree, current_worktree(worktree).git_dir, outside, dict(env or {}))


def execute(
    mode: str, case: Case, run_wtenv: Run
) -> tuple[int, list[FailedItem], list[Item], list[Item]]:
    """Run one of the four commands; return the exit status, `failed`, `already_absent`, `removed`.

    `removed` is `would_remove` for a dry run.
    """
    if mode == "dry-run":
        process = run_wtenv(["down", "--dry-run", "--json"], case.worktree, case.env)
        down = parse_down(process)
        return process.returncode, down.failed, down.already_absent, down.would_remove
    if mode == "down":
        process = run_wtenv(["down", "--json"], case.worktree, case.env)
        down = parse_down(process)
        return process.returncode, down.failed, down.already_absent, down.removed
    if mode == "gc":
        git(case.repo, "worktree", "remove", "--force", str(case.worktree))
        process = run_wtenv(["gc", "--json"], case.outside, case.env)
    else:
        shutil.rmtree(case.repo)
        process = run_wtenv(
            ["gc", "--release", str(case.worktree), "--json"], case.outside, case.env
        )
    result = parse_gc(process)
    return process.returncode, result.failed, result.already_absent, result.removed


def is_recorded(case: Case) -> bool:
    return case.git_dir in load().worktrees


def files_of(*paths: Path) -> dict[Path, bytes | None]:
    """Return the bytes of each path, or None for a path that does not exist."""
    return {path: path.read_bytes() if path.exists() else None for path in paths}


def expected_status(mode: str, *, failed: bool) -> int:
    return 13 if failed and mode != "dry-run" else 0


# === T177a: the compose project ===


@dataclass
class Decoy:
    """A compose project the test started: one container, one network, one volume with a file."""

    project: str
    resources: dict[str, list[str]]
    marker: str


def _compose_stack(directory: Path) -> None:
    (directory / "compose.yaml").write_text(
        "services:\n  decoy:\n"
        f"    image: {STACK_IMAGE}\n    pull_policy: never\n"
        '    entrypoint: ["sh", "-c", "echo decoy > /data/marker; exec sleep 3600"]\n'
        "    volumes:\n      - data:/data\nvolumes:\n  data:\n",
        encoding="utf-8",
    )


def _marker(project: str) -> str:
    """Read the file the decoy's container wrote into its volume."""
    container = project_resources(project)["containers"]
    if not container:
        return ""
    process = subprocess.run(
        ["docker", "exec", container[0], "cat", "/data/marker"],
        capture_output=True,
        text=True,
        check=False,
    )
    return process.stdout


@pytest.fixture
def start_decoy(tmp_path: Path, compose_image: str) -> Iterator[Callable[[str], Decoy]]:
    """Return a function that starts a decoy compose project by name; remove exactly those at the end."""
    started: list[str] = []

    def start(project: str) -> Decoy:
        directory = tmp_path / f"decoy-{len(started)}"
        directory.mkdir()
        _compose_stack(directory)
        started.append(project)
        subprocess.run(
            ["docker", "compose", "-p", project, "up", "-d", "--pull", "never"],
            cwd=directory,
            env=clean_environment(),
            capture_output=True,
            check=True,
        )
        resources = project_resources(project)
        assert all(resources.values()), resources
        marker = _marker(project)
        assert marker == "decoy\n", marker
        return Decoy(project, resources, marker)

    try:
        yield start
    finally:
        for project in started:
            with_nothing = tmp_path / "empty"
            with_nothing.mkdir(exist_ok=True)
            subprocess.run(
                ["docker", "compose", "-p", project, "down", "--volumes", "--remove-orphans"],
                cwd=with_nothing,
                env=clean_environment(),
                capture_output=True,
                check=False,
            )
    for project in started:
        left = {kind: ids for kind, ids in project_resources(project).items() if ids}
        assert not left, f"decoy project {project} left resources behind: {left}"


@pytest.fixture
def docker_log(tmp_path: Path) -> dict[str, str]:
    """Put a `docker` in front of the real one that logs every command line; return the env.

    The log lets a test prove that no `docker` command named a decoy, not even a listing.
    """
    real = shutil.which("docker")
    assert real is not None
    directory = tmp_path / "bin"
    directory.mkdir()
    log = tmp_path / "docker.log"
    log.write_text("", encoding="utf-8")
    script = directory / "docker"
    script.write_text(
        '#!/bin/sh\nprintf \'%s\\n\' "$*" >> "$WTENV_TEST_LOG"\nexec "$WTENV_TEST_REAL" "$@"\n'
    )
    script.chmod(0o755)
    return {
        "PATH": f"{directory}{os.pathsep}{os.environ['PATH']}",
        "WTENV_TEST_LOG": str(log),
        "WTENV_TEST_REAL": real,
    }


def docker_commands(env: dict[str, str]) -> str:
    return Path(env["WTENV_TEST_LOG"]).read_text(encoding="utf-8")


COMPOSE_TOML = 'ports = ["CACHE_PORT"]\nblock_size = 10\n\n[compose]\nfile = "compose.yaml"\n'


def stack_file(image: str) -> str:
    return (
        f"services:\n  cache:\n    image: {image}\n    pull_policy: never\n"
        '    ports:\n      - "${CACHE_PORT:-6379}:6379"\n'
    )


def state_of(decoy: Decoy) -> tuple[dict[str, list[str]], str]:
    return project_resources(decoy.project), _marker(decoy.project)


@pytest.mark.parametrize("mode", MODES)
@pytest.mark.parametrize("lookalike", [False, True], ids=["another name", "wtenv name, other id"])
def test_a_recorded_project_that_is_not_the_worktrees_own_is_never_listed_or_removed(
    lookalike: bool,
    mode: str,
    compose_image: str,
    run_wtenv: Run,
    make_repo: MakeRepo,
    add_worktree: AddWorktree,
    tmp_path: Path,
    start_decoy: Callable[[str], Decoy],
    docker_log: dict[str, str],
) -> None:
    """The decoy is a project of another name, or one named like a worktree's own with the id of
    another git directory (the main checkout's, say)."""
    other_git_dir = current_worktree(make_repo("other")).git_dir
    name = (
        f"wtenv-feature-x-{short_id(other_git_dir, 8)}"
        if lookalike
        else f"decoy-{uuid.uuid4().hex[:8]}"
    )
    decoy = start_decoy(name)
    case = provision(
        run_wtenv,
        make_repo,
        add_worktree,
        tmp_path,
        toml=COMPOSE_TOML,
        files={"compose.yaml": stack_file(compose_image)},
        env=docker_log,
    )
    hand_edit(case, lambda entry: entry["compose"].update(project=name))  # type: ignore[attr-defined]
    override = case.worktree / "compose.override.yaml"
    override_before = override.read_bytes()
    before = state_of(decoy)

    status, failed, _, _ = execute(mode, case, run_wtenv)

    assert status == expected_status(mode, failed=True)
    assert "compose_project" in [item.kind.value for item in failed]
    assert state_of(decoy) == before  # same ids, same file in the volume
    assert name not in docker_commands(docker_log)  # not even named
    assert is_recorded(case)
    if mode != "gc":  # the worktree directory is gone for `gc`
        assert override.read_bytes() == override_before
    entry = load().worktrees[case.git_dir]
    assert entry.compose is not None and entry.compose.project == name


# === T178b: volume names ===


@pytest.mark.parametrize("command", ["up", "down", "gc", "ls"])
def test_a_volumes_list_added_to_the_compose_record_makes_the_registry_unreadable(
    command: str,
    compose_image: str,
    run_wtenv: Run,
    make_repo: MakeRepo,
    add_worktree: AddWorktree,
    tmp_path: Path,
) -> None:
    """Volumes are found by the recorded project's label, never listed in the registry. A hand-added
    list is a field the schema does not have, so the file is refused and nothing is removed."""
    volume = f"wtenv-decoy-vol-{uuid.uuid4().hex[:8]}"
    case = provision(
        run_wtenv,
        make_repo,
        add_worktree,
        tmp_path,
        toml=COMPOSE_TOML,
        files={"compose.yaml": stack_file(compose_image)},
    )
    subprocess.run(["docker", "volume", "create", volume], check=True, capture_output=True)
    try:
        hand_edit(case, lambda entry: entry["compose"].update(volumes=[volume]))  # type: ignore[attr-defined]
        cwd = case.outside if command == "gc" else case.worktree

        process = run_wtenv([command, "--json"], cwd)

        assert process.returncode == 16, process.stdout + process.stderr
        assert json.loads(process.stdout)["error"]["code"] == "registry_unreadable"
        inspected = subprocess.run(
            ["docker", "volume", "inspect", volume], capture_output=True, check=False
        )
        assert inspected.returncode == 0  # the decoy volume is still there
    finally:
        subprocess.run(
            ["docker", "volume", "rm", "--force", volume], capture_output=True, check=False
        )
