"""`down` and `gc` use a recorded path only when it has the form wtenv records (T181, T183;
FR-039, FR-086; cli.md, `wtenv down`, "Recorded values").

The registry is a file a person can edit. A recorded env file, SQLite copy, or override that is
absolute, climbs out with `..`, or that normalisation would change is a `failed` item: nothing is
unlinked or rewritten, the record stays untouched, and the entry stays. Each case writes a decoy
where the value would lead, and checks it byte for byte. No Docker is needed: the compose project
is of the right form, and the removal of its resources is replaced by a function that finds none.
"""

import os
from pathlib import Path

import pytest

from wtenv import compose, registry, teardown
from wtenv.database import Removal
from wtenv.identity import recorded_path_problem
from wtenv.output import ItemKind, ResourceState
from wtenv.registry import (
    ComposeRecord,
    DatabaseRecord,
    EnvFileRecord,
    PortBlock,
    WorktreeEntry,
)

GIT_DIR = "/repos/app/.git/worktrees/app"
BEGIN = "# >>> wtenv managed (rewritten by `wtenv up`; do not edit) >>>"
END = "# <<< wtenv managed <<<"
SECTION = f"A=1\n{BEGIN}\nPORT=1\n{END}\n".encode()
HEADER = "# Generated by wtenv for this worktree. Do not edit or commit; `wtenv up` rewrites it.\n"
OWN_OVERRIDE = (HEADER + 'name: "x"\n').encode()


@pytest.fixture(autouse=True)
def no_docker(monkeypatch: pytest.MonkeyPatch) -> None:
    """The recorded project has no resources; no `docker` command is ever run."""

    def nothing_found(project: str, git_dir: str, **kwargs: object) -> Removal:
        return Removal()

    monkeypatch.setattr(compose, "remove_project", nothing_found)


# --- the helper ---------------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("path", "word"),
    [
        ("/etc/passwd", "absolute"),
        ("../x", "`..`"),
        ("a/../b", "`..`"),
        ("..", "`..`"),
        ("./a", "plain"),
        ("a//b", "plain"),
        ("a/", "plain"),
        (".", "plain"),
        ("", "empty"),
    ],
)
def test_a_path_of_a_form_wtenv_never_records_is_named_by_the_rule_it_breaks(
    path: str, word: str
) -> None:
    problem = recorded_path_problem(path)

    assert problem is not None and word in problem


@pytest.mark.parametrize("path", [".env.local", "a/b/.env", ".wtenv/dev.sqlite3", "compose.yaml"])
def test_a_relative_path_in_its_plain_form_has_no_problem(path: str) -> None:
    assert recorded_path_problem(path) is None


# --- what `down` does with a recorded path ------------------------------------------------------


@pytest.fixture
def root(tmp_path: Path) -> Path:
    path = tmp_path / "work" / "feature-x"
    path.mkdir(parents=True)
    return path


def entry_at(root: Path, **records: object) -> WorktreeEntry:
    return WorktreeEntry(
        git_dir=GIT_DIR,
        path=str(root),
        repository="/repos/app/.git",
        state="provisioned",
        block=PortBlock(start=20000, size=10),
        **records,  # type: ignore[arg-type]
    )


def env_record(path: str) -> EnvFileRecord:
    return EnvFileRecord(
        path=path, created_file=True, added_newline=False, state=ResourceState.CREATED
    )


def sqlite_record(path: str) -> DatabaseRecord:
    return DatabaseRecord(kind="sqlite", path=path, state=ResourceState.CREATED)


def compose_record(override: str) -> ComposeRecord:
    return ComposeRecord(
        project=compose.project_name("app", GIT_DIR),
        file="compose.yaml",
        override=override,
        override_state=ResourceState.CREATED,
    )


def record(entry: WorktreeEntry) -> None:
    with registry.transaction() as reg:
        reg.worktrees[entry.git_dir] = entry


def where_it_leads(root: Path, value: str) -> Path:
    """The file a value would lead to if it were used without a check."""
    return Path(os.path.normpath(os.path.join(root, value)))


# The value for a path under `root`, `outside` being a directory beside it, and the word the reason
# names the rule with.
BAD_VALUES = {
    "absolute": (lambda root: str(root.parent / "elsewhere" / "f"), "absolute"),
    "parent": (lambda root: "../f", "`..`"),
    "inside parent": (lambda root: "a/../f", "`..`"),
    "dot": (lambda root: "./f", "plain"),
    "double slash": (lambda root: "a//f", "plain"),
}


def put(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.parametrize("name", BAD_VALUES)
def test_a_recorded_env_file_of_a_form_wtenv_never_records_is_left_alone(
    name: str, dry_run: bool, root: Path
) -> None:
    value, word = BAD_VALUES[name][0](root), BAD_VALUES[name][1]
    decoy = where_it_leads(root, value)
    put(decoy, SECTION)
    original = env_record(value)
    entry = entry_at(root, env_file=original)
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert decoy.read_bytes() == SECTION
    assert [(f.kind, f.name) for f in release.failed] == [(ItemKind.ENV_SECTION, str(root / value))]
    assert word in release.failed[0].reason
    assert release.removed == [] and release.released is False
    assert registry.load().worktrees[GIT_DIR].env_file == original  # untouched, state included


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.parametrize("name", BAD_VALUES)
def test_a_recorded_sqlite_path_of_a_form_wtenv_never_records_is_left_alone(
    name: str, dry_run: bool, root: Path
) -> None:
    value, word = BAD_VALUES[name][0](root), BAD_VALUES[name][1]
    decoy = where_it_leads(root, value)
    sides = [Path(f"{decoy}{suffix}") for suffix in ("", "-wal", "-shm", "-journal")]
    for path in sides:
        put(path, f"mine: {path.name}".encode())
    original = sqlite_record(value)
    entry = entry_at(root, databases=[original])
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert [path.read_bytes() for path in sides] == [f"mine: {p.name}".encode() for p in sides]
    assert [(f.kind, f.name) for f in release.failed] == [(ItemKind.SQLITE_FILE, str(root / value))]
    assert word in release.failed[0].reason
    assert release.removed == [] and release.already_absent == []  # no side file is even listed
    assert registry.load().worktrees[GIT_DIR].databases == [original]


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.parametrize("value", ["data/x.db", ".wtenv/sub/x.db", "x.db", ".wtenv", ".wtenv/"])
def test_a_sqlite_copy_that_is_not_exactly_in_dot_wtenv_is_left_alone(
    value: str, dry_run: bool, root: Path
) -> None:
    decoy = where_it_leads(root, value)
    sides = [decoy, Path(f"{decoy}-wal")] if decoy.suffix == ".db" else []
    for path in sides:
        put(path, b"a database that is not wtenv's")
    original = sqlite_record(value)
    entry = entry_at(root, databases=[original])
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert all(path.read_bytes() == b"a database that is not wtenv's" for path in sides)
    assert [f.kind for f in release.failed] == [ItemKind.SQLITE_FILE]
    assert ".wtenv/" in release.failed[0].reason
    assert release.removed == [] and release.already_absent == []
    assert registry.load().worktrees[GIT_DIR].databases == [original]


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.parametrize("name", BAD_VALUES)
def test_a_recorded_override_of_a_form_wtenv_never_records_is_left_alone(
    name: str, dry_run: bool, root: Path
) -> None:
    value, word = BAD_VALUES[name][0](root), BAD_VALUES[name][1]
    decoy = where_it_leads(root, value)
    put(decoy, OWN_OVERRIDE)  # even a file that looks like wtenv's own
    original = compose_record(value)
    entry = entry_at(root, compose=original)
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert decoy.read_bytes() == OWN_OVERRIDE
    assert [(f.kind, f.name) for f in release.failed] == [
        (ItemKind.COMPOSE_OVERRIDE, str(root / value))
    ]
    assert word in release.failed[0].reason
    assert release.removed == [] and release.released is False
    assert registry.load().worktrees[GIT_DIR].compose == original


@pytest.mark.parametrize("dry_run", [True, False])
def test_a_recorded_path_that_has_the_form_wtenv_records_is_removed_as_before(
    dry_run: bool, root: Path
) -> None:
    put(root / ".env.local", SECTION)
    put(root / ".wtenv" / "dev.sqlite3", b"copy")
    put(root / "compose.override.yaml", OWN_OVERRIDE)
    entry = entry_at(
        root,
        env_file=env_record(".env.local"),
        databases=[sqlite_record(".wtenv/dev.sqlite3")],
        compose=compose_record("compose.override.yaml"),
    )
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert release.failed == []
    kinds = {item.kind for item in release.removed}
    assert {ItemKind.COMPOSE_OVERRIDE, ItemKind.SQLITE_FILE, ItemKind.ENV_SECTION} <= kinds
    assert (root / "compose.override.yaml").exists() is dry_run


# --- the override's name and its header (T183) ---------------------------------------------------


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.parametrize(
    "value",
    [
        "compose.yaml",
        "notes.override.yaml",
        "src/main.py",
        "compose.override.txt",
        "COMPOSE.override.yaml",
    ],
)
def test_an_override_whose_file_name_is_not_one_of_the_four_is_left_alone(
    value: str, dry_run: bool, root: Path
) -> None:
    put(root / value, OWN_OVERRIDE)  # with wtenv's header: only the name is wrong
    original = compose_record(value)
    entry = entry_at(root, compose=original)
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert (root / value).read_bytes() == OWN_OVERRIDE
    assert [(f.kind, f.name) for f in release.failed] == [
        (ItemKind.COMPOSE_OVERRIDE, str(root / value))
    ]
    assert "file name" in release.failed[0].reason
    assert registry.load().worktrees[GIT_DIR].compose == original


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.parametrize(
    "content",
    [
        b"services: {}\n",  # the developer's own
        b"",  # empty
        b"\n" + HEADER.encode() + b'name: "x"\n',  # the header is not the first line
        HEADER.encode().removesuffix(b"\n"),  # no line break after it
        b"# Generated by wtenv for another worktree.\n",
        HEADER.upper().encode(),
    ],
    ids=["developers", "empty", "header-second", "no-newline", "other-header", "upper-case"],
)
def test_an_override_that_does_not_start_with_wtenvs_header_is_left_alone(
    content: bytes, dry_run: bool, root: Path
) -> None:
    put(root / "compose.override.yaml", content)
    original = compose_record("compose.override.yaml")
    entry = entry_at(root, compose=original)
    record(entry)

    release = teardown.plan_release(entry) if dry_run else teardown.release_entry(entry)

    assert (root / "compose.override.yaml").read_bytes() == content
    assert [f.kind for f in release.failed] == [ItemKind.COMPOSE_OVERRIDE]
    assert "header" in release.failed[0].reason
    assert registry.load().worktrees[GIT_DIR].compose == original


@pytest.mark.parametrize("name", ["compose.override.yaml", "docker-compose.override.yml"])
def test_an_override_that_starts_with_wtenvs_header_and_has_one_of_the_names_is_removed(
    name: str, root: Path
) -> None:
    put(root / name, OWN_OVERRIDE)
    entry = entry_at(root, compose=compose_record(name))
    record(entry)

    release = teardown.release_entry(entry)

    assert release.failed == [] and not (root / name).exists()
    assert registry.load().worktrees.get(GIT_DIR) is None


def test_an_override_that_is_already_gone_is_absent_whatever_its_header_would_have_been(
    root: Path,
) -> None:
    entry = entry_at(root, compose=compose_record("compose.override.yaml"))
    record(entry)

    release = teardown.release_entry(entry)

    assert release.failed == []
    assert (ItemKind.COMPOSE_OVERRIDE, str(root / "compose.override.yaml")) in [
        (i.kind, i.name) for i in release.already_absent
    ]
