"""The compose project name and the generated override file (files.md, Names and Compose
override file; FR-028, FR-029; US3 scenario 4). The golden file is the example of files.md,
byte for byte."""

from pathlib import Path

import pytest

from wtenv import compose
from wtenv.compose import PortMapping
from wtenv.identity import short_id

GOLDEN = Path(__file__).parent / "golden" / "compose.override.yaml"


def mapping(
    service: str,
    target: int,
    published: str | None = "1",
    *,
    protocol: str = "tcp",
    host_ip: str | None = None,
    name: str | None = None,
    app_protocol: str | None = None,
) -> PortMapping:
    return PortMapping(
        service=service,
        target=target,
        protocol=protocol,
        host_ip=host_ip,
        published=published,
        mode="ingress",
        name=name,
        app_protocol=app_protocol,
    )


# --- the golden file ---------------------------------------------------------------------------


def test_the_example_input_generates_the_golden_file_byte_for_byte() -> None:
    assigned = [
        (mapping("db", 5432), 20011),
        (mapping("cache", 6379), 20012),
    ]

    text = compose.override_text("wtenv-feature-x-3f9a1c2b", assigned)

    assert text.encode() == GOLDEN.read_bytes()


def test_generating_twice_gives_identical_bytes() -> None:
    assigned = [(mapping("db", 5432), 20011), (mapping("cache", 6379), 20012)]

    first = compose.override_text("wtenv-a-00000000", assigned)

    assert compose.override_text("wtenv-a-00000000", assigned) == first


# --- the layout --------------------------------------------------------------------------------


def test_services_are_in_name_order_whatever_the_order_given() -> None:
    assigned = [
        (mapping("web", 80), 20010),
        (mapping("api", 81), 20011),
        (mapping("db", 82), 20012),
    ]

    text = compose.override_text("wtenv-a-00000000", assigned)

    keys = [line.strip() for line in text.splitlines() if line.startswith('  "')]
    assert keys == ['"api":', '"db":', '"web":']


def test_a_service_with_several_ports_lists_them_in_the_order_given() -> None:
    assigned = [(mapping("web", 81), 20011), (mapping("web", 80), 20010)]

    text = compose.override_text("wtenv-a-00000000", assigned)

    lines = [line for line in text.splitlines() if line.startswith("      - ")]
    assert [json_target(line) for line in lines] == [81, 80]
    assert text.count("ports: !override") == 1


def json_target(line: str) -> int:
    return int(line.split('"target": ')[1].split(",")[0])


def test_every_field_compose_reported_is_repeated_in_order_with_only_published_changed() -> None:
    assigned = [
        (
            mapping(
                "db",
                5432,
                "5433",
                protocol="udp",
                host_ip="127.0.0.1",
                name="pg",
                app_protocol="pgwire",
            ),
            20011,
        )
    ]

    text = compose.override_text("wtenv-a-00000000", assigned)

    assert (
        '      - {"target": 5432, "published": "20011", "protocol": "udp", "mode": "ingress", '
        '"host_ip": "127.0.0.1", "name": "pg", "app_protocol": "pgwire"}\n'
    ) in text
    assert "5433" not in text


def test_the_published_port_is_a_string_and_the_target_a_number() -> None:
    text = compose.override_text("wtenv-a-00000000", [(mapping("web", 80), 20010)])

    assert '"target": 80,' in text
    assert '"published": "20010"' in text


def test_strings_are_written_with_json_quoting() -> None:
    assigned = [(mapping('we"b', 80, name="é\\x"), 20010)]

    text = compose.override_text("wtenv-a-00000000", assigned)

    assert '  "we\\"b":\n' in text
    assert '"name": "\\u00e9\\\\x"' in text


def test_no_published_ports_leaves_the_name_alone() -> None:
    text = compose.override_text("wtenv-a-00000000", [])

    assert text == (
        "# Generated by wtenv for this worktree. Do not edit or commit; `wtenv up` rewrites it.\n"
        'name: "wtenv-a-00000000"\n'
    )


def test_the_file_ends_with_one_newline() -> None:
    text = compose.override_text("wtenv-a-00000000", [(mapping("web", 80), 20010)])

    assert text.endswith("}\n")
    assert not text.endswith("\n\n")


# --- names -------------------------------------------------------------------------------------


def test_the_project_name_is_wtenv_slug_id8_with_dashes() -> None:
    git_dir = "/code/repo/.git/worktrees/feature-x"

    name = compose.project_name("Feature_X!", git_dir)

    assert name == f"wtenv-feature-x-{short_id(git_dir, 8)}"


def test_an_empty_slug_becomes_wt() -> None:
    assert compose.project_name("!!!", "/g").startswith("wtenv-wt-")


@pytest.mark.parametrize(
    ("compose_file", "override"),
    [
        ("compose.yaml", "compose.override.yaml"),
        ("compose.yml", "compose.override.yml"),
        ("docker-compose.yaml", "docker-compose.override.yaml"),
        ("docker-compose.yml", "docker-compose.override.yml"),
    ],
)
def test_the_override_file_name_for_each_default_compose_file_name(
    compose_file: str, override: str
) -> None:
    assert compose.override_file_name(compose_file) == override


def test_another_compose_file_name_has_no_override_name() -> None:
    with pytest.raises(ValueError, match="stack.yaml"):
        compose.override_file_name("stack.yaml")


def test_the_override_path_is_beside_the_compose_file() -> None:
    assert compose.override_path("compose.yaml") == "compose.override.yaml"
    assert (
        compose.override_path("deploy/docker-compose.yml") == "deploy/docker-compose.override.yml"
    )


def test_all_four_override_names_are_listed() -> None:
    assert compose.OVERRIDE_FILE_NAMES == (
        "compose.override.yaml",
        "compose.override.yml",
        "docker-compose.override.yaml",
        "docker-compose.override.yml",
    )
